project:
  type: website
  output-dir: docs

website:
  title: "RNP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - blog.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



